[theme]
primaryColor = "#2e7d32"          # Hijau utama
backgroundColor = "#f5f9f6"       # Hijau sangat muda (background)
secondaryBackgroundColor = "#e0f2f1" # Box/container
textColor = "#263238"             # Teks abu gelap
font = "sans serif"
